### PR TITLE
added method to find column index by header value

### PR DESCRIPTION
**Pull request by trusche**
Hi! I found myself implementing a variation of this method several times in various projects to assist in parsing existing spreadsheets - perhaps it can be of use to others as well.

### CODE REVIEW

**Comment by weshatheleopard** [comment]
There is no such concept as "header" in Excel: if somebody chooses to put their table headers in the first row of the sheet, that does not automatically mean that *everybody* does the same thing. As such, this code is not universally applicable and does not belong in the library.

**Comment by trusche** [comment]
Fair enough -- although I'd argue that it's a common enough convention to warrant inclusion. But I'll monkeypatch instead. Thanks for the great gem!

**Comment by trusche** [comment]
@rastarobot that's an idea. A bit overkill for now, but if we run into other often used conventions that don't properly belong in the core gem, I'll consider it.

**Comment by weshatheleopard** [comment]
Actually ```convenience_methods.rb``` is slated to be extracted into a separate "convenience" module at some point.

**Comment by trusche** [comment]
Cool - I'll keep an eye on it and will be happy to contribute.

**Pull request closed without merging**
