### PR TITLE
Remove illegal characters if it includes

### PR DESCRIPTION
**Pull request by sachin21**
Fixes https://github.com/weshatheleopard/rubyXL/issues/243

I think rubyXL should have filtering function. because until merge this pull request, We have to implement filtering function by each of the export.

I exported by rubyXL and encountered an error with [broken.xlsx](https://github.com/weshatheleopard/rubyXL/files/773138/broken.xlsx) on Excel.

### CODE REVIEW

**Comment by purintai** [comment]
@weshatheleopard Could you confirm and merge this?

**Comment by weshatheleopard** [comment]
As they say, "Computer is like a windmill: grain in, flour out; garbage in, garbage out."

If you don't want illegal chars in your data, how about you do not **put** them in your data?

**Comment by sachin21** [comment]
I think the threshing machine has a function for the filter shit. Like it, If exported .xlsx file was including illegal strings, It mistakes the means for the end.
If not merged, We have to write reinventing the wheel of removing illegal strings.

Would you reconsider this? @weshatheleopard

**Comment by weshatheleopard** [comment]
In that case, just as you said, "the threshing machine has a function for the filter mouse's shit", so the setter for cell.value should have the filter for illegal characters and throw an error if somebody tries to insert illegal character into a cell — just like Excel does. If you want to (thoughtfully) implement something like that, please go ahead, I will add it to the code.

**Comment by sachin21** [comment]
@weshatheleopard I understand. I will implmenet it at new pull-req. I'm closing this pull-req.

**Pull request closed without merging**
