### PR TITLE
use ruby style code

### PR DESCRIPTION
**Pull request by zhisme**
Let's do it the rubyish way :)

### CODE REVIEW

**Comment by zhisme** [comment]
any comment?
I'm not a medium.

**Comment by weshatheleopard** [comment]
The changes you proposed do not fundamentally modify anything, and I as you might have noticed, I do not favor the "do-end" style of execution blocks.

**Comment by zhisme** [comment]
Fair enough. It will be awesome if you would add some text contribution part saying. No style code fixes, no markdown. Only working code.

**Comment by weshatheleopard** [comment]
I just don't want to end up in a situation where there are 2 conflicting people who believe something need to be styled in a very particular way fighting over it without any productive output.

**Pull request closed without merging**
