### PR TITLE
Updates Worksheet#merged_cells when insert/delete row/column

### PR DESCRIPTION
**Pull request by labocho**
In a workbook with merged cells, the following methods do not update the range of merged cells.

* `RubyXL::Worksheet#insert_row`
* `RubyXL::Worksheet#remove_row`
* `RubyXL::Worksheet#insert_column`
* `RubyXL::Worksheet#remove_column`

I added lines of code to update the range of merged cells for the methods.

### CODE REVIEW

**Comment by weshatheleopard** [comment]
From the first look at it, you've done a great job! I'm going to take a better look a tad later, and merge your PR, thank you!

**Review by weshatheleopard — APPROVED** [review]

**Comment by labocho** [comment]
Thank you ! 😃

**Comment by weshatheleopard** [comment]
@labocho I really liked your throughness with this PR. Would you like to become a co-owner of this project?

**Comment by labocho** [comment]
@weshatheleopard 
I'm honored by your evaluation!
But I was working on the gem at work. And the project was done, so I cannot take time for it now...
Sorry...

**Pull request merged**
